project:
  type: website
  output-dir: docs

website:
  title: "Bazaar"
  page-navigation: true
  reader-mode: true

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorials"
        href: posts/tutorials/index.qmd
      - text: "Blog Posts"
        href: posts/blog_posts/index.qmd
  
  sidebar:
    - contents: auto
  # - title: "Tutorials"
  #   style: "docked"
  #   contents:
  #     - posts/tutorials/jax_tutorial/index.qmd
  #     - posts/tutorials/kalman_bayesian_filters_tutorial/index.qmd
  #   sort: "date desc"

  # - title: "Blog"
  #   style: "docked"
  #   contents: posts/blog_posts
  #   sort: "date desc"

format:
  html:
    theme: minty
    css: styles.css

toc: true
toc-title: "What's on this page"
number-sections: true

execute:
  freeze: auto
